#!/usr/bin/env zsh
STATUS="$(ps aux | grep -v grep |grep dimland)"

icon() {
    if [[ "$STATUS" == "" ]]; then
        echo ""
    else
        echo ""
    fi
}

toggle() {
    if [[ $STATUS == "" ]]; then
        dimland -a 0.2 &
        notify-send -i $HOME/tool/nightlight.jpg --urgency=normal "Shadow" "Shadow has been turned on!"
    else
        ps aux | grep -v grep |grep dimland | awk '{print $2}' | xargs kill
        notify-send -i $HOME/tool/sunlight.jpeg --urgency=normal "Shadow" "Shadow has been turned off!"
    fi
}

status() {
    if [[ $STATUS == "" ]]; then
        echo "Off"
    else
        echo "On"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
fi
